PORTNAME=	tgcrypto
PORTVERSION=	1.2.5
CATEGORIES=	net-im python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	TgCrypto-${DISTVERSION}

MAINTAINER=	florian@wagner-flo.de
COMMENT=	Fast and Portable Cryptography Extension Library for Pyrogram
WWW=		https://pypi.org/project/TgCrypto/

LICENSE=	LGPL3

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}setuptools>0:devel/py-setuptools@${PY_FLAVOR}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
