# $FreeBSD$

PORTNAME=	fbsjail
MASTERDIR=	${.CURDIR}/../fbsdist
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist
DATADIR=	${PREFIX}/share/fbsdist
RUN_DEPENDS+=	fbsdist>0:sysutils/fbsdist

.include "${MASTERDIR}/Makefile"
