# Created by: Florian Wagner <florian@wagner-flo.net>
# $FreeBSD$

PORTNAME=	fbsjail
MASTERDIR=	${.CURDIR}/../fbsdist
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist
DATADIR=	${PREFIX}/share/fbsdist

.include "${MASTERDIR}/Makefile"
