PORTNAME=		mod_authn_dovecot
DISTVERSION=		0.2.4
DISTVERSIONPREFIX=	v
CATEGORIES=		www

MAINTAINER=	florian@wagner-flo.net
COMMENT=	Apache authentication against Dovecot
LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	bmanojlovic
GH_PROJECT=	mod_authn_dovecot

USES=		apache:2.4
AP_FAST_BUILD=	yes

.include <bsd.port.mk>
